version: "3.8"

services:
  db:
    image: postgres:15
    container_name: integram-db
    restart: always
    environment:
      POSTGRES_DB: integram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

volumes:
  pg_data:
