name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.11"

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Run Pytest
  #       run: |
  #         pytest tests/

  deploy:
    # needs: test
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519_server horhe@185.112.102.186 << EOF
            cd ~/integram
            git pull origin main

            docker compose down
            docker compose pull || true

            DB_HOST=${DB_HOST} \
            DB_PORT=${DB_PORT} \
            DB_NAME=${DB_NAME} \
            DB_USER=${DB_USER} \
            DB_PASSWORD=${DB_PASSWORD} \
            docker compose up -d --build
            cd .sql_to_load
            ./upload_methods.sh
          EOF
